### ISSUE TITLE
您好，您每篇文章的顶部图用什么软件做的，谢谢！

### ISSUE THREAD

**Issue by dongzl** [mrdear/blog-comment#47]
您好，您每篇文章的顶部图用什么软件做的，谢谢！

**Comment by mrdear** [comment]
@dongzl 

软件: sketch

设置画板尺寸,然后设定一个背景作为基础模板.

每个文章头图copy基础模板后,加上logo等标识就行了.

**Comment by dongzl** [comment]
> @dongzl
> 
> 软件: sketch
> 
> 设置画板尺寸,然后设定一个背景作为基础模板.
> 
> 每个文章头图copy基础模板后,加上logo等标识就行了.

感谢您反馈，我也学习一下！另外您有些图做的感觉很好，比如 spring/java/设计模式，封面图文字效果也很漂亮，如果我直接使用一下，您介意吗？

**Comment by mrdear** [comment]
> > @dongzl
> > 软件: sketch
> > 设置画板尺寸,然后设定一个背景作为基础模板.
> > 每个文章头图copy基础模板后,加上logo等标识就行了.
> 
> 感谢您反馈，我也学习一下！另外您有些图做的感觉很好，比如 spring/java/设计模式，封面图文字效果也很漂亮，如果我直接使用一下，您介意吗？

随便使用哈。

**Comment by dongzl** [comment]
> 随便使用哈。

非常感谢您分享，我按照您说的软件自己试了一下，的确很不错，和您交流学到了很多！^_^
